// flow-typed signature: a4f72b2593fa8f0baa510619826bbc35
// flow-typed version: <<STUB>>/bs58_v4.0.1/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs58'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs58' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bs58/index' {
  declare module.exports: $Exports<'bs58'>;
}
declare module 'bs58/index.js' {
  declare module.exports: $Exports<'bs58'>;
}
