// flow-typed signature: 33d8c68eb5019fd5d28a2e50a322865b
// flow-typed version: <<STUB>>/csv_v5.3./flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv/lib/es5' {
  declare module.exports: any;
}

declare module 'csv/lib/es5/sync' {
  declare module.exports: any;
}

declare module 'csv/lib' {
  declare module.exports: any;
}

declare module 'csv/lib/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv/lib/es5/index' {
  declare module.exports: $Exports<'csv/lib/es5'>;
}
declare module 'csv/lib/es5/index.js' {
  declare module.exports: $Exports<'csv/lib/es5'>;
}
declare module 'csv/lib/es5/sync.js' {
  declare module.exports: $Exports<'csv/lib/es5/sync'>;
}
declare module 'csv/lib/index' {
  declare module.exports: $Exports<'csv/lib'>;
}
declare module 'csv/lib/index.js' {
  declare module.exports: $Exports<'csv/lib'>;
}
declare module 'csv/lib/sync.js' {
  declare module.exports: $Exports<'csv/lib/sync'>;
}
