// flow-typed signature: 6c0225c087c82bbf35f8e3d66b9d44ce
// flow-typed version: <<STUB>>/generate-password_v1.5.1/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generate-password'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generate-password' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generate-password/example' {
  declare module.exports: any;
}

declare module 'generate-password/main' {
  declare module.exports: any;
}

declare module 'generate-password/src/generate' {
  declare module.exports: any;
}

declare module 'generate-password/test/generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generate-password/example.js' {
  declare module.exports: $Exports<'generate-password/example'>;
}
declare module 'generate-password/main.js' {
  declare module.exports: $Exports<'generate-password/main'>;
}
declare module 'generate-password/src/generate.js' {
  declare module.exports: $Exports<'generate-password/src/generate'>;
}
declare module 'generate-password/test/generator.js' {
  declare module.exports: $Exports<'generate-password/test/generator'>;
}
