// flow-typed signature: b45bc1666c6467ce83b1ab809eec80db
// flow-typed version: <<STUB>>/hive-serving-request_v1.0.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hive-serving-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hive-serving-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hive-serving-request/Cli' {
  declare module.exports: any;
}

declare module 'hive-serving-request/Example' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/amqplib_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/aws-sdk_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/bluebird_v3.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/del_v3.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/flow-copy-source_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/request_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/flow-typed/npm/sanitize-filename_vx.x.x' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/AmqpChannelCache' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/ConsulServiceDiscovery' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/HiveServingError' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/HslClient' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/HslClientConsul' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/Index' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/Retry' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/RpcClient' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/Tracing' {
  declare module.exports: any;
}

declare module 'hive-serving-request/lib/Types' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/AmqpChannelCache' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/ConsulServiceDiscovery' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/HiveServingError' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/HslClient' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/HslClientConsul' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/Index' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/Retry' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/RpcClient' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/Tracing' {
  declare module.exports: any;
}

declare module 'hive-serving-request/src/Types' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/live/HiveServingRequestApi' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/live/Test' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/AmqpChannelCache.test' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/ConsulServiceDiscoveryTest' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/HslClient.test' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/HslClientMockHSC.test' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/MockAmqp' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/MockHSC' {
  declare module.exports: any;
}

declare module 'hive-serving-request/test/unit/Retry.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hive-serving-request/Cli.js' {
  declare module.exports: $Exports<'hive-serving-request/Cli'>;
}
declare module 'hive-serving-request/Example.js' {
  declare module.exports: $Exports<'hive-serving-request/Example'>;
}
declare module 'hive-serving-request/flow-typed/npm/amqplib_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/amqplib_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/aws-sdk_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/aws-sdk_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/bluebird_v3.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/bluebird_v3.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/del_v3.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/del_v3.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/flow-copy-source_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/flow-copy-source_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/request_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/request_vx.x.x'>;
}
declare module 'hive-serving-request/flow-typed/npm/sanitize-filename_vx.x.x.js' {
  declare module.exports: $Exports<'hive-serving-request/flow-typed/npm/sanitize-filename_vx.x.x'>;
}
declare module 'hive-serving-request/lib/AmqpChannelCache.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/AmqpChannelCache'>;
}
declare module 'hive-serving-request/lib/ConsulServiceDiscovery.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/ConsulServiceDiscovery'>;
}
declare module 'hive-serving-request/lib/HiveServingError.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/HiveServingError'>;
}
declare module 'hive-serving-request/lib/HslClient.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/HslClient'>;
}
declare module 'hive-serving-request/lib/HslClientConsul.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/HslClientConsul'>;
}
declare module 'hive-serving-request/lib/Index.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/Index'>;
}
declare module 'hive-serving-request/lib/Retry.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/Retry'>;
}
declare module 'hive-serving-request/lib/RpcClient.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/RpcClient'>;
}
declare module 'hive-serving-request/lib/Tracing.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/Tracing'>;
}
declare module 'hive-serving-request/lib/Types.js' {
  declare module.exports: $Exports<'hive-serving-request/lib/Types'>;
}
declare module 'hive-serving-request/src/AmqpChannelCache.js' {
  declare module.exports: $Exports<'hive-serving-request/src/AmqpChannelCache'>;
}
declare module 'hive-serving-request/src/ConsulServiceDiscovery.js' {
  declare module.exports: $Exports<'hive-serving-request/src/ConsulServiceDiscovery'>;
}
declare module 'hive-serving-request/src/HiveServingError.js' {
  declare module.exports: $Exports<'hive-serving-request/src/HiveServingError'>;
}
declare module 'hive-serving-request/src/HslClient.js' {
  declare module.exports: $Exports<'hive-serving-request/src/HslClient'>;
}
declare module 'hive-serving-request/src/HslClientConsul.js' {
  declare module.exports: $Exports<'hive-serving-request/src/HslClientConsul'>;
}
declare module 'hive-serving-request/src/Index.js' {
  declare module.exports: $Exports<'hive-serving-request/src/Index'>;
}
declare module 'hive-serving-request/src/Retry.js' {
  declare module.exports: $Exports<'hive-serving-request/src/Retry'>;
}
declare module 'hive-serving-request/src/RpcClient.js' {
  declare module.exports: $Exports<'hive-serving-request/src/RpcClient'>;
}
declare module 'hive-serving-request/src/Tracing.js' {
  declare module.exports: $Exports<'hive-serving-request/src/Tracing'>;
}
declare module 'hive-serving-request/src/Types.js' {
  declare module.exports: $Exports<'hive-serving-request/src/Types'>;
}
declare module 'hive-serving-request/test/live/HiveServingRequestApi.js' {
  declare module.exports: $Exports<'hive-serving-request/test/live/HiveServingRequestApi'>;
}
declare module 'hive-serving-request/test/live/Test.js' {
  declare module.exports: $Exports<'hive-serving-request/test/live/Test'>;
}
declare module 'hive-serving-request/test/unit/AmqpChannelCache.test.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/AmqpChannelCache.test'>;
}
declare module 'hive-serving-request/test/unit/ConsulServiceDiscoveryTest.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/ConsulServiceDiscoveryTest'>;
}
declare module 'hive-serving-request/test/unit/HslClient.test.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/HslClient.test'>;
}
declare module 'hive-serving-request/test/unit/HslClientMockHSC.test.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/HslClientMockHSC.test'>;
}
declare module 'hive-serving-request/test/unit/MockAmqp.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/MockAmqp'>;
}
declare module 'hive-serving-request/test/unit/MockHSC.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/MockHSC'>;
}
declare module 'hive-serving-request/test/unit/Retry.test.js' {
  declare module.exports: $Exports<'hive-serving-request/test/unit/Retry.test'>;
}
