// flow-typed signature: 65aeea405dedf2387fa26568e55dde7c
// flow-typed version: <<STUB>>/uuid-base62_v0.1.0/flow_v0.138.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid-base62'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid-base62' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid-base62/compare' {
  declare module.exports: any;
}

declare module 'uuid-base62/test/uuid-base62.test' {
  declare module.exports: any;
}

declare module 'uuid-base62/uuid-base62' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid-base62/compare.js' {
  declare module.exports: $Exports<'uuid-base62/compare'>;
}
declare module 'uuid-base62/test/uuid-base62.test.js' {
  declare module.exports: $Exports<'uuid-base62/test/uuid-base62.test'>;
}
declare module 'uuid-base62/uuid-base62.js' {
  declare module.exports: $Exports<'uuid-base62/uuid-base62'>;
}
