export const AUTH_CONSTANTS = {
  REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',

  LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  FETCH_PROFILE_REQUEST: 'AUTH_FETCH_PROFILE_REQUEST',
  FETCH_PROFILE_SUCCESS: 'AUTH_FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'AUTH_FETCH_PROFILE_FAILURE',

  LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
}
